---
- name: Find all machines in the cluster
  register: cluster_machines
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:ClusterId": "{{ onyx_cluster_id }}"

- name: Ensure Cluster cache directory exists
  file:
    path: "{{ cluster_cache | dirname }}"
    state: directory
    mode: 0755

- name: Cache the cluster information locally
  run_once: yes
  delegate_to: localhost
  copy:
    content: "{{ cluster_machines.instances | to_nice_json }}"
    dest: "{{ cluster_cache }}"
