---
- include: vpc.yml
  when: create_vpc

- include: sgs.yml
  when: create_sgs

- include: remove_vpc.yml
  when: remove_vpc

- include: ec2.yml
  when: create_ec2

- include: cache.yml
  when: cache

- include: populate_inventory.yml
  when: populate_inventory
