---
- name: Find all relevant machines
  register: discovered_machines
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      instance-state-name: running
      "tag:Name": "[{{ onyx_cluster_id }}] {{ profile_id }}"
      "tag:ClusterId": "{{ onyx_cluster_id }}"
      "tag:ProfileId": "{{ profile_id }}"

- name: Add machines host to inventory
  add_host:
    name: "{{ item.public_dns_name }}"
    private_ip: "{{ item.private_ip_address }}"
    groups: "{{ profile_id }}"
  with_items: discovered_machines.instances
