---
- name: Remove subnets and route tables from the VPC
  local_action:
    module: ec2_vpc
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    state: present
    resource_tags: "{}"
    subnets: []
    internet_gateway: no
    route_tables: []
    wait: yes

- name: Delete the VPC
  local_action:
    module: ec2_vpc
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    state: absent
    resource_tags: "{}"
    wait: yes