---
- name: "Create the {{ service }} security group"
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    name: "[{{ onyx_cluster_id }}] {{ service }} Security Group"
    description: "Security group for {{ service }}"
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules: "{{ service_security_rules }}"
